name: Test Workflow
on:
  push:
    branches:
      [main,dev]
      tags: [v.*.*.*]
    pull_request:
      branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: |
          pytest
      - name: Upload Test Results
        if: faliure()
        uses: actions/upload-artifact@v4
        with:
          name: test-results